Caption: "Заголовок отчёта"
CaptionBackgroundColor: "#4472C4"
HeaderBackgroundColor: "#D9E1F2"
CsvDelimiter: ";"
Depersonalization:
  PlaceholderFile: "depersonalization.yaml"
  OutputSuffix: "_depersonalized"
Replacement:
  PlaceholderFile: "replacements.yaml"
  OutputSuffix: "_replaced"
Personalization:
  OutputSuffix: "_personalized"
ZebraColors:
  - "#F2F2F2"
  - "#FFFFFF"
Columns:
  - Input: "некоторая задача"
    OutputIndex: 1
    Output: "Задача"
    DefaultValue: "DEFAULT"
  - Input: "номер задачи"
    OutputIndex: 2
    Output: "Номер задачи"
    DefaultValue: "-"
  - Input: "некоторый текст"
    OutputIndex: 3
    Output: "Текст"
    DefaultValue: "Empty"
  - Input: "Имя"
    OutputIndex: 4
    OutputGroup: "Имя"
  - OutputIndex: 5
    Output: "Описание"
    DefaultValues:
      - "А1:"
      - "Б1:"
  - Input: "Время"
    OutputIndex: 6
    Output: "Время"
    MathRound: "/ 2"
  - OutputIndex: 8
    Output: "Новая Колонка2"
    DefaultValue: "--"