Caption: "Заголовок отчёта"
CaptionBackgroundColor: "#4472C4"
HeaderBackgroundColor: "#D9E1F2"
CsvDelimiter: ";"
Depersonalization:
  PlaceholderFile: "depersonalization.yaml"
  OutputSuffix: "_depersonalized"
  Replacements:
    - Find: "Ivan"
      Replace: "Pedro"
      WholeWordMatch: true
    - Find: "Dmitry"
      Replace: "Hans"
      WholeWordMatch: true
Replacement:
  PlaceholderFile: "replacements.yaml"
  OutputSuffix: "_replaced"
  Replacements:
    - Find: "задача"
      Replace: "task N"
      WholeWordMatch: false
    - Find: "эта задача"
      Replace: "задача"
      WholeWordMatch: true
Personalization:
  OutputSuffix: "_personalized"
ZebraColors:
  - "#F2F2F2"
  - "#FFFFFF"
AI:
  - url: "http://localhost:11434"
    name: "Ollama"
Columns:
  - Input: "некоторая задача"
    OutputIndex: 1
    Output: "Задача"
    DefaultValue: "DEFAULT Task"
  - Input: "номер задачи"
    OutputIndex: 2
    Output: "Номер задачи"
    DefaultValue: "-"
  - Input: "некоторый текст"
    OutputIndex: 3
    Output: "Текст"
    DefaultValue: "Empty"
  - Input: "Имя"
    OutputIndex: 4
    OutputGroup: "Имя"
  - OutputIndex: 5
    Output: "Описание"
    DefaultValues:
      - "Часть 1:"
      - "Часть 2:"
